
# 指定使用的log4j2配置文件
logging:
  config: classpath:log4j2.xml
  
# 开启Actuator 配置
endpoints: 
  shutdown: 
    enabled: true
management: 
  security: 
    enabled: false

apollo:
  bootstrap:
    enabled: true
    namespaces: wanshunCar.redis,wanshunCar.mysql,wanshunCar.mongo,wanshunCar.zk,wanshunCar.kafka,wanshunCar.commSystemConfig,wanshunCar.motan,application,wanshunCar.FastDFS,wanshunCar.clusterJob
