#ifndef LLJZ_DISK_PROTOCOL_H_
#define LLJZ_DISK_PROTOCOL_H_

namespace lljz {
namespace disk {

//uint16_t [1,65535]
//server type
enum ServerType {
   SERVER_TYPE_CONFIG_SERVER=1,   //配置服务
   SERVER_TYPE_ACCESS_SERVER=2,   //接入服务
   SERVER_TYPE_ACCOUNT_SERVER=3,  //账号服务
   SERVER_TYPE_FILE_SERVER=4,    //文件服务器

   SERVER_TYPE_CLIENT_LINUX=65000,  //linux客户端
   SERVER_TYPE_PYTHON_CLIENT_LINUX=65001  //linux python客户端
};

//public
enum PublicMsg {
   //回显调试
   PUBLIC_ECHO_TEST_REQ=0,
   PUBLIC_ECHO_TEST_RESP=1,

   //注册
   PUBLIC_REGISTER_REQ=2,
   PUBLIC_REGISTER_RESP=3
};

//config_server
enum ConfigServerMsg{
   //获取服务列表
   CONFIG_SERVER_GET_SERVICE_LIST_REQ=1000,
   CONFIG_SERVER_GET_SERVICE_LIST_RESP=1001
};

//account_server
enum AccountServerMsg {
   ACCOUNT_SERVER_REGISTER_ACCOUNT_REQ=1000,//注册账号
   ACCOUNT_SERVER_REGISTER_ACCOUNT_RESP=1001,

   ACCOUNT_SERVER_SET_ACCOUNT_INFO_REQ=1002,//设置账号信息
   ACCOUNT_SERVER_SET_ACCOUNT_INFO_RESP=1003,

   ACCOUNT_SERVER_MODIFY_LOGIN_PASSWORD_REQ=1004,//修改登陆密码
   ACCOUNT_SERVER_MODIFY_LOGIN_PASSWORD_RESP=1005,

   ACCOUNT_SERVER_LOGIN_REQ=1006,//登陆
   ACCOUNT_SERVER_LOGIN_RESP=1007,

   ACCOUNT_SERVER_LOGOUT_REQ=1008,//登出
   ACCOUNT_SERVER_LOGOUT_RESP=1009
};

//file_server
enum FileServerMsg {
   //新建文件夹
   FILE_SERVER_CREATE_FOLDER_REQ=1000,
   FILE_SERVER_CREATE_FOLDER_RESP=1001,

   //修改文件/文件夹属性
   FILE_SERVER_MODIFY_PROPERTY_REQ=1002,
   FILE_SERVER_MODIFY_PROPERTY_RESP=1003,

   //上传文件
   FILE_SERVER_UPLOAD_FILE_REQ=1004,
   FILE_SERVER_UPLOAD_FILE_RESP=1005,

   //下载文件
   FILE_SERVER_DOWNLOAD_FILE_REQ=1006,
   FILE_SERVER_DOWNLOAD_FILE_RESP=1007,

   //
   FILE_SERVER_DOWNLOAD_FILE_GET_INFO_REQ=1008,
   FILE_SERVER_DOWNLOAD_FILE_GET_INFO_RESP=1009,

   //
   FILE_SERVER_DOWNLOAD_FILE_BY_SEQ_NO_REQ=1010,
   FILE_SERVER_DOWNLOAD_FILE_BY_SEQ_NO_RESP=1011,

/*
   //删除文件/文件夹
   FILE_SERVER_DELETE_FILE_OR_FOLDER_REQ=1012,
   FILE_SERVER_DELETE_FILE_OR_FOLDER_RESP=1013,

   //查找文件
   FILE_SERVER_SEARCH_FILE_REQ=1014,
   FILE_SERVER_SEARCH_FILE_RESP=1015

*/

};

}
}
#endif