build:
	g++ test.cpp -I/home/lljz/lib/include/tbnet \
	-I/home/lljz/lib/include/tbsys \
	-I/home/lljz/lib/include \
	/home/lljz/lib/lib/libtfsclient.a \
	/home/lljz/lib/lib/libtbnet.a \
	/home/lljz/lib/lib/libtbsys.a  -lpthread -lpthread -lrt
